SET NAMES UTF8;

DROP DATABASE IF EXISTS xfn;

CREATE DATABASE xfn CHARSET=UTF8;

USE xfn;

CREATE TABLE xfn_admin(
  aid INT PRIMARY KEY AUTO_INCREMENT,
  aname VARCHAR(32) UNIQUE,
  apwd VARCHAR(64)
);

CREATE TABLE xfn_setting(
  sid INT 
)